# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CircleLite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Pods for CircleLite

  target 'CircleLiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CircleLite-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CircleLite-tvOS

  target 'CircleLite-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
